---
#Hostname of your application server, (or group if you are deploying to multiple)
- hosts: nginx.internal
  #User that owns the directories below.
  user: merge
  vars:
    #repo containing your project
    gitrepo: git@github.com:PaperElectron/ansible-node-tmux.git
    #Destination directory 
    gitdest: /home/prod_usr/node/prod_app
    #Desired git branch
    gitbranch: master
    #Location the application writes it pid file too
    pidfile: /home/merge/node/prod_app/pid.txt
    #Tmux session name and window number that ansible should send its commands to.
    tmuxsession: prodAPP:1
    #Path to Node.js executable.
    appPath: /home/prod_usr/node/prod_app/app
    #Node.js executable name.
    nodeapp: app.js
    #Desired NODE_ENV variable
    nodeenv: production
  tasks:
  - name: Git Checkout current Branch
    git: repo={{gitrepo}}
         dest={{gitdest}}
         version={{gitbranch}}

  - name: NPM update via package.json
    npm: path={{appPath}}

  - name: Get pid from pid.txt if it exists
    command: cat {{pidfile}} removes={{pidfile}}
    register: pid_contents

  - name: Stop Node Process if running
    command: kill -2 ${pid_contents.stdout} removes={{pidfile}}
    when: pid_contents.stdout > 1

  - name: Change Directories
    command: tmux send-keys -t {{tmuxsession}} "cd {{appPath}}" "ENTER"
    
  - name: Pause to ensure correct state
    pause: seconds=5

  - name: Start Node Process if not running
    command: tmux send-keys -t {{tmuxsession}} "NODE_ENV={{nodeenv}} node {{appPath}}/{{nodeapp}}" "ENTER"
    async: 10
    poll: 0