---
- hosts: nginx.internal
  user: merge
  vars:
    gitrepo: git@bitbucket.org:MonsterTKE/vapemerge.git
    gitdest: /home/merge/node/merge_app
    gitbranch: master
    pidfile: /home/merge/node/merge_app/pid.txt
    tmuxsession: mergeAPP:1
    appPath: /home/merge/node/merge_app/app
    nodeapp: app.js
    nodeenv: development
  tasks:
  - name: Git Checkout current Branch
    git: repo={{gitrepo}}
         dest={{gitdest}}
         version={{gitbranch}}

  - name: NPM update via package.json
    npm: path={{appPath}}

  - name: Get pid from pid.txt if it exists
    command: cat {{pidfile}} removes={{pidfile}}
    register: pid_contents

  - name: Stop Node Process if running
    command: kill -2 ${pid_contents.stdout} removes={{pidfile}}
    when: pid_contents.stdout > 1

  - name: Change Directories
    command: tmux send-keys -t {{tmuxsession}} "cd {{appPath}}" "ENTER"
    
  - name: Pause to ensure correct state
    pause: seconds=5

  - name: Start Node Process if not running
    command: tmux send-keys -t {{tmuxsession}} "NODE_ENV={{nodeenv}} node {{appPath}}/{{nodeapp}}" "ENTER"
    async: 10
    poll: 0